server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###com.mysql.cj.jdbc.Driver com.mysql.jdbc.Driver
  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: none
    # 控制台显示SQL
    show-sql: true
  redis:
    host: 192.168.87.128
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 1
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8085
spring:
  profiles: prod